// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/auth.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pkg "github.com/nuts-foundation/nuts-auth/pkg"
)

// MockAuthClient is a mock of AuthClient interface
type MockAuthClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthClientMockRecorder
}

// MockAuthClientMockRecorder is the mock recorder for MockAuthClient
type MockAuthClientMockRecorder struct {
	mock *MockAuthClient
}

// NewMockAuthClient creates a new mock instance
func NewMockAuthClient(ctrl *gomock.Controller) *MockAuthClient {
	mock := &MockAuthClient{ctrl: ctrl}
	mock.recorder = &MockAuthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthClient) EXPECT() *MockAuthClientMockRecorder {
	return m.recorder
}

// CreateContractSession mocks base method
func (m *MockAuthClient) CreateContractSession(sessionRequest pkg.CreateSessionRequest) (*pkg.CreateSessionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContractSession", sessionRequest)
	ret0, _ := ret[0].(*pkg.CreateSessionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContractSession indicates an expected call of CreateContractSession
func (mr *MockAuthClientMockRecorder) CreateContractSession(sessionRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContractSession", reflect.TypeOf((*MockAuthClient)(nil).CreateContractSession), sessionRequest)
}

// ContractSessionStatus mocks base method
func (m *MockAuthClient) ContractSessionStatus(sessionID string) (*pkg.SessionStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractSessionStatus", sessionID)
	ret0, _ := ret[0].(*pkg.SessionStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractSessionStatus indicates an expected call of ContractSessionStatus
func (mr *MockAuthClientMockRecorder) ContractSessionStatus(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractSessionStatus", reflect.TypeOf((*MockAuthClient)(nil).ContractSessionStatus), sessionID)
}

// NewContractByType mocks base method
func (m *MockAuthClient) ContractByType(contractType pkg.ContractType, language pkg.Language, version pkg.Version) (*pkg.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewContractByType", contractType, language, version)
	ret0, _ := ret[0].(*pkg.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewContractByType indicates an expected call of NewContractByType
func (mr *MockAuthClientMockRecorder) ContractByType(contractType, language, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewContractByType", reflect.TypeOf((*MockAuthClient)(nil).ContractByType), contractType, language, version)
}

// ValidateContract mocks base method
func (m *MockAuthClient) ValidateContract(request pkg.ValidationRequest) (*pkg.ContractValidationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateContract", request)
	ret0, _ := ret[0].(*pkg.ContractValidationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateContract indicates an expected call of ValidateContract
func (mr *MockAuthClientMockRecorder) ValidateContract(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateContract", reflect.TypeOf((*MockAuthClient)(nil).ValidateContract), request)
}

// CreateAccessToken mocks base method
func (m *MockAuthClient) CreateAccessToken(request pkg.CreateAccessTokenRequest) (*pkg.AccessTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessToken", request)
	ret0, _ := ret[0].(*pkg.AccessTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessToken indicates an expected call of CreateAccessToken
func (mr *MockAuthClientMockRecorder) CreateAccessToken(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessToken", reflect.TypeOf((*MockAuthClient)(nil).CreateAccessToken), request)
}

// CreateJwtBearerToken mocks base method
func (m *MockAuthClient) CreateJwtBearerToken(request pkg.CreateJwtBearerTokenRequest) (*pkg.JwtBearerTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJwtBearerToken", request)
	ret0, _ := ret[0].(*pkg.JwtBearerTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJwtBearerToken indicates an expected call of CreateJwtBearerToken
func (mr *MockAuthClientMockRecorder) CreateJwtBearerToken(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJwtBearerToken", reflect.TypeOf((*MockAuthClient)(nil).CreateJwtBearerToken), request)
}

// IntrospectAccessToken mocks base method
func (m *MockAuthClient) IntrospectAccessToken(token string) (*pkg.NutsAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntrospectAccessToken", token)
	ret0, _ := ret[0].(*pkg.NutsAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntrospectAccessToken indicates an expected call of IntrospectAccessToken
func (mr *MockAuthClientMockRecorder) IntrospectAccessToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntrospectAccessToken", reflect.TypeOf((*MockAuthClient)(nil).IntrospectAccessToken), token)
}

// KeyExistsFor mocks base method
func (m *MockAuthClient) KeyExistsFor(legalEntity string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyExistsFor", legalEntity)
	ret0, _ := ret[0].(bool)
	return ret0
}

// KeyExistsFor indicates an expected call of KeyExistsFor
func (mr *MockAuthClientMockRecorder) KeyExistsFor(legalEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyExistsFor", reflect.TypeOf((*MockAuthClient)(nil).KeyExistsFor), legalEntity)
}

// OrganizationNameByID mocks base method
func (m *MockAuthClient) OrganizationNameByID(legalEntity string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizationNameByID", legalEntity)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrganizationNameByID indicates an expected call of OrganizationNameByID
func (mr *MockAuthClientMockRecorder) OrganizationNameByID(legalEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizationNameByID", reflect.TypeOf((*MockAuthClient)(nil).OrganizationNameByID), legalEntity)
}
